EthicalML/awesome-production-machine-learning

README.md
I just learned about your awesome list, so I would like to add some items :)
=> Added neptune.ml and steppy to your awesome list

README.md
Hi! This repo is great.
Just added comet.ml as one of the options
=> Adding comet.ml to the list

README.md
* Add MLflow, Sacred, FGLab, Studio.ML, OpenWhisk, Google Cloud Machine Learning Engine, Microsoft Azure Machine Learning service, IBM Watson Machine Learning, Datmo, Valohai, Dataiku, MCenter, Skafos, SKIL, MLJAR, MissingLink, DataRobot, and RiseML.
* Fix formatting of PMML and BigDL.
* Make Pachyderm YouTube video start from the beginning.
=> Add 18 platforms, reformat existing resources

README.md
Auto-Magical Experiment Manager & Version Control for AI
=> Add TRAINS

README.md
the link pointed to a completely different repository
=> fix link on "Maintained" badge

README.md
=> Missing url for automl-gs

README.md
Open-source Python package - a toolkit for auditing and mitigating bias and fairness of machine learning systems
https://docs.responsibly.ai
https://github.com/ResponsiblyAI/responsibly
=> Add responsibly Python package

README.md
Under "Data Pipeline ETL Frameworks" (as discussed in https://github.com/EthicalML/awesome-production-machine-learning/pull/27)
=> Add Neuraxle

README.md
A few related projects in this PR.
=> Add Hopsworks Feature Store, Enterprise distribtion, and Maggy Framework

README.md
Add [metaflow](https://github.com/Netflix/metaflow) under **Data Pipeline ETL Frameworks** section.
=> add netflix-metaflow

README.md
=> Add Substra to privacy preserving machine learning

README.md
Add prodigy, kedro-viz, ETL pipelines, chronos, gokart
=> Add prodigy, kedro-viz, ETL pipelines, chronos, gokart

README.md
Added Modin, CuPy, CuDf, CuML, NumpyGroupies, Vespa, Beam, DEAP, Perspective, Weld
Moved Ray to "Computation load distribution frameworks" section.
=> Modin, CuPy, CuDf, CuML, NumpyGroupies, Vespa, Beam, DEAP, Perspective, Weld

README.md
=> remove yhat

README.md
=> remove riseml

README.md
I've added mljar-supervised in two categories: interpretation and feature engineering.
=> add mljar-supervised

README.md
The organization of Feast has changed to "feast-dev" from "gojek"
=> Fix Feast organization

README.md
@axsaucedo New commercial product added to list.
=> Add D2iQ KUDO for Kubeflow

README.md
=> adding Outlier and Anomaly Detection section

README.md
I added a link to _KUDO for Kubeflow_ that describes the background and assumptions that went into the product.
=> Add link to introductory post on KUDO for Kubeflow

README.md
Love the list! ⭐
Surprised the very popular H2O-3 platform was missing (named as one of the [greatest apps ever written](https://blogs.oracle.com/javamagazine/the-top-25-greatest-java-apps-ever-written) by Java Magazine).  This PR adds it to the list.  I took the description from the official repo and shortened it as appropriate to fit with the style of the list.  I'm happy to make any necessary style adjustments.
Also added H2O's Driverless AI to the list under commercial offerings following the style of its neighbors on that list.
Thanks!
=> Add H2O-3 and Driverless AI to the list.

README.md
Hey, @axsaucedo. Added DAGsHub to the category per your request.
Thanks for the quick response!
=> Added DAGsHub to Platforms

README.md
Hey,
just adding a missing star badge in.
Cheers!
=> Add missing star badge

README.md
* Commercial Platform Section
* One-liner: "ML DataOps platform providing various tools to build, label, manage and iterate on training data."
Great repository. Our platform also aims to help bringing machine learning to our lives, by easing up all the heavy liftings with data.
=> Add Superb AI

README.md
PyTorch Lightning is an open source research framework designed for rapid research iterations. See more in https://github.com/PyTorchLightning/pytorch-lightning
=> Add PyTorch Lightning to awesome-production-machine-learning

README.md
Added the entry to the commerical products list.
=> Scribble feature store

README.md
Hi all, 
Great repo with very useful resources. 💯 
Adding Apache Zeppelin to the notebooks section. 📓
=> Include apache zeppelin

README.md
-> Open SDK in tools section
-> Commercial side in commercial section
Hopefully put in right spot! :)
=> Add Diffgram

README.md
=> Added metadata store section

README.md
- Add ML Metadata
- Add Model Card Toolkit
=> Add ML Metadata and Model Card Toolkit to Metadata Management

README.md
TerminusDB is an open source project for distributed version control of graph storage, in the same kind of space as DVC which is included.
https://ai-infrastructure.org/how-the-canonical-stack-for-machine-learning-will-unleash-the-next-generation-of-cutting-edge-ai-apps/ - lists it as a potential component of the "Canonical Stack" for production ML
=> Add TerminusDB to data version control list

README.md
Hi all,
Thanks for your awesome repo 👍 
Adding [SETL](https://github.com/SETL-Developers/setl).
SETL is a Scala framework powered by Apache Spark that helps you structure your Spark ETL projects, modularize your data transformation logic, and speed up your development.
=> Add SETL to Data Pipeline ETL Frameworks

README.md
https://github.com/intel-analytics/analytics-zoo
A unified Data Analytics and AI platform for distributed TensorFlow, Keras and PyTorch on Apache Spark/Flink & Ray
=> Add Analytics Zoo

README.md
ZenML is an open-source MLOps framework for reproducible ML pipelines. It's focussed on extensibility, guaranteed reproducibility of pipelines, easy integrations to other tools (e.g. Kubernetes, different Cloud providers), caching, metadata tracking.
For additional information, check [https://github.com/maiot-io/zenml](https://github.com/maiot-io/zenml)
=> adding ZenML

README.md
Assuming alphabetical ordering.
=> Add Backprop

README.md
Added Apache superset in the section - Industrial Strength Visualisation libraries
=> added superset in industrial strength visualisation libraries

README.md
Added Syndicai to Commerical Platforms.
[Syndicai](https://syndicai.co) is a cloud-agnostic platform for organizations to deploy, manage and scale enterprise-grade AI models & pipelines without unnecessary complexity.
=> Add Syndicai Platform

README.md
=> update alluxio github repo site

README.md
Tool for creating custom Dataset for Named Entity Recognition Projects
=> Brat Text Annotation Tool

README.md
Delta Lake is a storage layer that brings scalable, ACID transactions to Apache Spark and other big-data engines.
=> add Delta Lake

README.md
Would highly appreciate it if you list our product - the Censius AI Observability Platform into this repo. Thanks.
=> Add Censius to Commercial Platform 

README.md
MLEM helps you package and deploy machine learning models. It saves ML models in a standard format that can be used in a variety of production scenarios, such as real-time REST serving or batch processing.
Iterative Studio, combining the power of leading open-source tools.
Best Regards...
=> Add MLEM and Iterative Studio 🌟

README.md
This PR aims to add new tools to metadata management module.
=> Add new tools to metadata management

README.md
This PR aims to scrub and solve the formatting issue in markdown preview.
=> Scrub and unify formatting issues 

README.md
Reddit has acquired this company, and its official website has been taken off forever. Check the website for confirmation :)
https://www.redditinc.com/blog/reddit-acquires-machine-learning-platform-spell
=> remove spell

README.md
cleanlab nicely complements any labeling tool and is very useful to assess data & label quality
=> add cleanlab to Labeling Tools section

README.md
According to discussion https://github.com/EthicalML/awesome-production-machine-learning/pull/313 since most feature engineering optimization techniques/tools in out list lie under autoML
=> merge feature engineering into autoML larger domain

README.md
Intrigued by EdgeGPT, one of the most promising applications of cross-modal machine learning is neural search. Thus I intend to create a new module named "neural search". The core idea of neural search is to leverage state-of-the-art deep neural networks to build every component of a search system. In short, neural search is deep neural network-powered information retrieval. Notably, neural search is not equal to neural architecture search.
Reference:
https://jina.ai/news/what-is-neural-search-and-learn-to-build-a-neural-search-engine
https://medium.com/jina-ai/what-is-jina-and-neural-search-7a9e166608ab
=> Create Neural Search Module

README.md
=> add anomaly detection tools

README.md
=> Add TensorStore

README.md
Aqueduct is an open-source MLOps framework that allows you to write code in vanilla Python, run that code on any cloud infrastructure you'd like to use, and gain visibility into the execution and performance of your models and predictions.
=> Add Aqueduct to the list

README.md
adding arize-phoenix as an open source tool for model serving and monitoring
=> Update README.md to add arize phoenix

README.md
I have temporarily merged this. If this really does not work, I can roll back... @axsaucedo
=> remove multi badge and refine x badge

README.md
As discussed before, most entries listed here are not tools anymore, they are just company names, we remove them for unity with our awsome list nature.
=> remove commercial section

README.md
make the module naming more clear since it is more related model storage optimization (just like data storage optimization)
=> refine Model Storage Optimisation naming

README.md
Contains:
* Updating old links / references
* Adding suggestion to watch repo to get notified via releases; created https://github.com/EthicalML/awesome-production-machine-learning/issues/622 to enhance notifications
=> Updating old links and watch suggestion

README.md
Reverts EthicalML/awesome-production-machine-learning#633
=> Revert "unify metadata and feature into model, data, experiment management se…"

README.md
This PR materializes https://github.com/EthicalML/awesome-production-machine-learning/issues/419
=> create industry strength dataset

README.md
This small PR fixes a few broken references and typos in `README.md`.
=> Fix Agentic Framework reference
